{{
    config(
        materialized='table'
    )
}}

-- This model flattens the raw JSON record and casts fields to their appropriate data types.

with source as (

    select raw_record
    from {{ source('probate_raw', 'PROBATE_FILINGS_ENRICHED') }}

),

extracted as (

    select
        -- The unique identifier for this record, extracted from the JSON
        raw_record:probate_lead_case_number::string as probate_lead_case_number,

        -- Dates
        try_to_date(raw_record:probate_lead_filing_date::string) as probate_lead_filing_date,
        try_to_date(raw_record:rp_file_date::string) as rp_file_date,
        try_to_date(raw_record:statement_date::string) as statement_date,

        -- Booleans
        try_to_boolean(raw_record:is_owner_grantee::string) as is_owner_grantee,
        try_to_boolean(raw_record:is_owner_grantor::string) as is_owner_grantor,
        try_to_boolean(raw_record:is_potential_decedent_match::string) as is_potential_decedent_match,
        try_to_boolean(raw_record:needs_review_flag::string) as needs_review_flag,

        -- Numerics (Scores, Values, Counts)
        try_to_numeric(raw_record:date_proximity_score::string) as date_proximity_score,
        try_to_numeric(raw_record:days_apart::string) as days_apart,
        try_to_numeric(raw_record:hcad_appraised_value_summary::string) as hcad_appraised_value_summary,
        try_to_numeric(raw_record:hcad_bedrooms::string) as hcad_bedrooms,
        try_to_numeric(raw_record:hcad_building_area_count::string) as hcad_building_area_count,
        try_to_numeric(raw_record:hcad_best_property_fit_score::string) as hcad_best_property_fit_score,
        try_to_numeric(raw_record:hcad_full_bathrooms::string) as hcad_full_bathrooms,
        try_to_numeric(raw_record:hcad_garage_sqft::string) as hcad_garage_sqft,
        try_to_numeric(raw_record:hcad_grade_adjustment::string) as hcad_grade_adjustment,
        try_to_numeric(raw_record:hcad_half_bathrooms::string) as hcad_half_bathrooms,
        try_to_numeric(raw_record:hcad_impr_total_sqft::string) as hcad_impr_total_sqft,
        try_to_numeric(raw_record:hcad_improvement_market_value::string) as hcad_improvement_market_value,
        try_to_numeric(raw_record:hcad_land_line_count::string) as hcad_land_line_count,
        try_to_numeric(raw_record:hcad_land_market_value::string) as hcad_land_market_value,
        try_to_numeric(raw_record:hcad_land_market_value_total::string) as hcad_land_market_value_total,
        try_to_numeric(raw_record:hcad_list_page_summary_rank_score::string) as hcad_list_page_summary_rank_score,
        try_to_numeric(raw_record:hcad_lot_sqft_total::string) as hcad_lot_sqft_total,
        try_to_numeric(raw_record:hcad_market_value_summary::string) as hcad_market_value_summary,
        try_to_numeric(raw_record:hcad_sqft_summary::string) as hcad_sqft_summary,
        try_to_numeric(raw_record:hcad_total_base_sqft::string) as hcad_total_base_sqft,
        try_to_numeric(raw_record:hcad_total_structure_sqft::string) as hcad_total_structure_sqft,
        try_to_numeric(raw_record:hctax_appraised_value::string) as hctax_appraised_value,
        try_to_numeric(raw_record:hctax_improvements_market_value::string) as hctax_improvements_market_value,
        try_to_numeric(raw_record:hctax_land_market_value::string) as hctax_land_market_value,
        try_to_numeric(raw_record:hctax_total_market_value::string) as hctax_total_market_value,
        try_to_numeric(raw_record:instrument_weight::string) as instrument_weight,
        try_to_numeric(raw_record:match_score_total::string) as match_score_total,
        try_to_numeric(raw_record:name_first_score::string) as name_first_score,
        try_to_numeric(raw_record:name_last_score::string) as name_last_score,
        try_to_numeric(raw_record:party_role_score::string) as party_role_score,
        try_to_numeric(raw_record:rp_legal_block::string) as rp_legal_block,
        try_to_numeric(raw_record:rp_legal_lot::string) as rp_legal_lot,
        try_to_numeric(raw_record:rp_legal_sec::string) as rp_legal_sec,
        try_to_numeric(raw_record:rp_signal_strength::string) as rp_signal_strength,
        try_to_numeric(raw_record:score_hcad_vs_best_rp_grantee::string) as score_hcad_vs_best_rp_grantee,
        try_to_numeric(raw_record:score_hcad_vs_probate::string) as score_hcad_vs_probate,
        try_to_numeric(raw_record:score_hcad_vs_rp_party::string) as score_hcad_vs_rp_party,
        try_to_numeric(raw_record:score_probate_vs_rp_party::string) as score_probate_vs_rp_party,
        try_to_numeric(raw_record:search_tier_weight::string) as search_tier_weight,
        try_to_numeric(raw_record:total_current_taxes_due::string) as total_current_taxes_due,
        try_to_numeric(raw_record:taxes_due_by_jan31::string) as taxes_due_by_jan31,

        -- JSON Objects (kept as VARIANT)
        raw_record:hcad_appraised_history_json as hcad_appraised_history_json,
        raw_record:hcad_building_data_json as hcad_building_data_json,
        raw_record:hcad_land_data_json as hcad_land_data_json,
        raw_record:hcad_other_characteristics_json as hcad_other_characteristics_json,

        -- All other fields as strings
        raw_record:account_status_text::string as account_status_text,
        raw_record:account_to_search::string as account_to_search,
        raw_record:cleaned_probate_lead_decedent_first::string as cleaned_probate_lead_decedent_first,
        raw_record:cleaned_probate_lead_decedent_last::string as cleaned_probate_lead_decedent_last,
        raw_record:cleaned_rp_party_first_name::string as cleaned_rp_party_first_name,
        raw_record:cleaned_rp_party_last_name::string as cleaned_rp_party_last_name,
        raw_record:contact_target_tier::string as contact_target_tier,
        raw_record:error::string as error,
        raw_record:exemption_code::string as exemption_code,
        raw_record:hcad_account::string as hcad_account,
        raw_record:hcad_account_summary::string as hcad_account_summary,
        raw_record:hcad_address_summary::string as hcad_address_summary,
        raw_record:hcad_appraised_value_detail::string as hcad_appraised_value_detail,
        raw_record:hcad_detail_url::string as hcad_detail_url,
        raw_record:hcad_detail_url_visited::string as hcad_detail_url_visited,
        raw_record:hcad_exterior_wall::string as hcad_exterior_wall,
        raw_record:hcad_final_tier_hit::string as hcad_final_tier_hit,
        raw_record:hcad_foundation_type::string as hcad_foundation_type,
        raw_record:hcad_heating_ac::string as hcad_heating_ac,
        raw_record:hcad_legal_desc_detail::string as hcad_legal_desc_detail,
        raw_record:hcad_mailing_address::string as hcad_mailing_address,
        raw_record:hcad_market_value_detail::string as hcad_market_value_detail,
        raw_record:hcad_owner_full_name::string as hcad_owner_full_name,
        raw_record:hcad_owner_match_type::string as hcad_owner_match_type,
        raw_record:hcad_owner_summary::string as hcad_owner_summary,
        raw_record:hcad_physical_condition::string as hcad_physical_condition,
        raw_record:hcad_search_status::string as hcad_search_status,
        raw_record:hcad_site_address::string as hcad_site_address,
        raw_record:hcad_zip_summary::string as hcad_zip_summary,
        raw_record:hctax_account::string as hctax_account,
        raw_record:hctax_legal_desc_full::string as hctax_legal_desc_full,
        raw_record:hctax_owner_full_name::string as hctax_owner_full_name,
        raw_record:hctax_owner_mailing_address::string as hctax_owner_mailing_address,
        raw_record:hctax_site_address::string as hctax_site_address,
        raw_record:match_confidence_level::string as match_confidence_level,
        raw_record:owner_contact_name::string as owner_contact_name,
        raw_record:owner_contact_rationale::string as owner_contact_rationale,
        raw_record:prior_years_taxes_due::string as prior_years_taxes_due,
        raw_record:probate_lead_county::string as probate_lead_county,
        raw_record:probate_lead_decedent_first::string as probate_lead_decedent_first,
        raw_record:probate_lead_decedent_last::string as probate_lead_decedent_last,
        raw_record:probate_lead_signal_strength::string as probate_lead_signal_strength,
        raw_record:probate_lead_status::string as probate_lead_status,
        raw_record:probate_lead_subtype::string as probate_lead_subtype,
        raw_record:probate_lead_type_desc::string as probate_lead_type_desc,
        raw_record:probate_name::string as probate_name,
        raw_record:review_reason::string as review_reason,
        raw_record:rp_file_number::string as rp_file_number,
        raw_record:rp_found_by_search_term::string as rp_found_by_search_term,
        raw_record:rp_grantee_full_names_list::string as rp_grantee_full_names_list,
        raw_record:rp_instrument_type::string as rp_instrument_type,
        raw_record:rp_legal_abstract::string as rp_legal_abstract,
        raw_record:rp_legal_description_text::string as rp_legal_description_text,
        raw_record:rp_legal_tract::string as rp_legal_tract,
        raw_record:rp_party_first_name::string as rp_party_first_name,
        raw_record:rp_party_full_name::string as rp_party_full_name,
        raw_record:rp_party_last_name::string as rp_party_last_name,
        raw_record:rp_party_type::string as rp_party_type,
        raw_record:rp_search_tier::string as rp_search_tier,
        raw_record:soundex_decedent_last::string as soundex_decedent_last,
        raw_record:soundex_rp_party_last::string as soundex_rp_party_last,
        

    from source
    -- Filter out records that are missing the core identifier
    where raw_record:probate_lead_case_number is not null
      and raw_record:probate_lead_case_number::string != ''

),

final as (

    -- Re-order the columns to match the exact order provided,
    -- ensuring consistency for downstream models.
    select
        account_status_text,
        account_to_search,
        cleaned_probate_lead_decedent_first,
        cleaned_probate_lead_decedent_last,
        cleaned_rp_party_first_name,
        cleaned_rp_party_last_name,
        contact_target_tier,
        date_proximity_score,
        days_apart,
        error,
        exemption_code,
        hcad_account,
        hcad_account_summary,
        hcad_address_summary,
        hcad_appraised_history_json,
        hcad_appraised_value_detail,
        hcad_appraised_value_summary,
        hcad_bedrooms,
        hcad_best_property_fit_score,
        hcad_building_area_count,
        hcad_building_data_json,
        hcad_detail_url,
        hcad_detail_url_visited,
        hcad_exterior_wall,
        hcad_final_tier_hit,
        hcad_foundation_type,
        hcad_full_bathrooms,
        hcad_garage_sqft,
        hcad_grade_adjustment,
        hcad_half_bathrooms,
        hcad_heating_ac,
        hcad_impr_total_sqft,
        hcad_improvement_market_value,
        hcad_land_data_json,
        hcad_land_line_count,
        hcad_land_market_value,
        hcad_land_market_value_total,
        hcad_legal_desc_detail,
        hcad_list_page_summary_rank_score,
        hcad_lot_sqft_total,
        hcad_mailing_address,
        hcad_market_value_detail,
        hcad_market_value_summary,
        hcad_other_characteristics_json,
        hcad_owner_full_name,
        hcad_owner_match_type,
        hcad_owner_summary,
        hcad_physical_condition,
        hcad_search_status,
        hcad_site_address,
        hcad_sqft_summary,
        hcad_total_base_sqft,
        hcad_total_structure_sqft,
        hcad_zip_summary,
        hctax_account,
        hctax_appraised_value,
        hctax_improvements_market_value,
        hctax_land_market_value,
        hctax_legal_desc_full,
        hctax_owner_full_name,
        hctax_owner_mailing_address,
        hctax_site_address,
        hctax_total_market_value,
        instrument_weight,
        is_owner_grantee,
        is_owner_grantor,
        is_potential_decedent_match,
        match_confidence_level,
        match_score_total,
        name_first_score,
        name_last_score,
        needs_review_flag,
        owner_contact_name,
        owner_contact_rationale,
        party_role_score,
        prior_years_taxes_due,
        probate_lead_case_number,
        probate_lead_county,
        probate_lead_decedent_first,
        probate_lead_decedent_last,
        probate_lead_filing_date,
        probate_lead_signal_strength,
        probate_lead_status,
        probate_lead_subtype,
        probate_lead_type_desc,
        probate_name,
        review_reason,
        rp_file_date,
        rp_file_number,
        rp_found_by_search_term,
        rp_grantee_full_names_list,
        rp_instrument_type,
        rp_legal_abstract,
        rp_legal_block,
        rp_legal_description_text,
        rp_legal_lot,
        rp_legal_sec,
        rp_legal_tract,
        rp_party_first_name,
        rp_party_full_name,
        rp_party_last_name,
        rp_party_type,
        rp_search_tier,
        rp_signal_strength,
        score_hcad_vs_best_rp_grantee,
        score_hcad_vs_probate,
        score_hcad_vs_rp_party,
        score_probate_vs_rp_party,
        search_tier_weight,
        soundex_decedent_last,
        soundex_rp_party_last,
        statement_date,
        taxes_due_by_jan31,
        total_current_taxes_due
    from extracted

)

select * from final